name: save_me_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  dio: ^5.4.3+1
  file_picker: ^8.0.5
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  hexcolor: ^3.0.1
  intl: ^0.19.0
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/deeptalk.png
    - assets/images/favicon.png
    - assets/images/kompasimg.png
    - assets/images/kompasicon.png
    - assets/images/verified.png
    - assets/images/webinar.png
    - assets/images/reporting.png
    - assets/images/sumguy.png
    - assets/images/reportingimg.jpg
